sign created database in gensync

diff --git a/scripts/gensync b/scripts/gensync
--- a/scripts/gensync
+++ b/scripts/gensync
@@ -1,25 +1,25 @@
 #!/bin/bash
-# 
+#
 #   gensync
-#  
+#
 #   Copyright (c) 2005 by Aurelien Foret <orelien@chez.com>
 #   Copyright (c) 2005 by Judd Vinet <jvinet@zeroflux.org>
 #   Copyright (c) 2005 by Christian Hamar <krics@linuxforum.hu>
 #   Copyright (c) 2005, 2006, 2007, 2008, 2010 by Miklos Vajna <vmiklos@frugalware.org>
-#  
+#
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation; either version 2 of the License, or
 #   (at your option) any later version.
-# 
+#
 #   This program is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.
-#  
+#
 #   You should have received a copy of the GNU General Public License
 #   along with this program; if not, write to the Free Software
-#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
+#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
 #   USA.
 #
 
@@ -301,6 +301,13 @@ echo "gensync: compressing to $destfile..." >&2
 cd $gstmpdir
 fakeroot tar --use-compress-program=xz -cf $destfile $extra *
 [ $? -gt 0 ] && die "error writing to $destfile"
+
+if [ -z "$DB_KEY" ]; then
+	echo "WARNING: skipping database signing. no key was specified."
+else
+	gpg --detach-sign --armor --local-user "$DB_KEY" "$destfile"
+	[ $? -ne 0 ] && echo "WARNING: signing the database failed. please investigate."
+fi
 
 rm -rf $gstmpdir
 fi
