makepkg: if the version infos are missing, bail out with an error warnigns are ignored by many and the given FrugalBuild is probably broken. if one really needs the old version, then use makepkg -u

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -999,7 +999,9 @@ if [ "$NOUP2DATE" = "0" ]; then
 		fi
 	fi
 	if [ -z "$up2date" ]; then
-		warning "Version checking informations are missing. Cannot check for newer version."
+			echo "   FAILED" >&2
+			error "There was no output!"
+			exit 1
 	else
 		if [ "$pkgver" != "$up2date" ]; then
 			echo "   FAILED" >&2
