makepkg: s/warning/error/ if can't create subpackages

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -782,6 +782,50 @@ if ! in_array $CARCH ${archs[@]}; then
 	exit 1
 fi
 
+if [ ! -z "$subpkgs" ]; then
+	goodsubpkgs=1
+	if [ "${#subdescs[@]}" != 0 ] && [ "${#subdescs[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#sublicense[@]}" != 0 ] && [ "${#sublicense[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subreplaces[@]}" != 0 ] && [ "${#subreplaces[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subgroups[@]}" != 0 ] && [ "${#subgroups[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subdepends[@]}" != 0 ] && [ "${#subdepends[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subrodepends[@]}" != 0 ] && [ "${#subrodepends[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subremoves[@]}" != 0 ] && [ "${#subremoves[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subconflicts[@]}" != 0 ] && [ "${#subconflicts[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subprovides[@]}" != 0 ] && [ "${#subprovides[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subbackup[@]}" != 0 ] && [ "${#subbackup[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#subinstall[@]}" != 0 ] && [ "${#subinstall[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ "${#suboptions[@]}" != 0 ] && [ "${#suboptions[@]}" != "${#subpkgs[@]}" ]; then
+		goodsubpkgs=0
+	fi
+	if [ $goodsubpkgs -ne 1 ]; then
+		error "Subpackage infos are incomplete. Cannot create subpackages."
+		exit 1
+	fi
+fi
+
 if [ -f $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm -a "$FORCE" = "0" -a "$GENSHA1" = "0" ]; then
 	if [ "$INSTALL" = "1" ]; then
 		warning "a package has already been built, installing existing package."
@@ -1405,68 +1449,27 @@ fi
 
 create_pkg $pkgname
 if [ ! -z "$subpkgs" ]; then
-	goodsubpkgs=1
-	if [ "${#subdescs[@]}" != 0 ] && [ "${#subdescs[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#sublicense[@]}" != 0 ] && [ "${#sublicense[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subreplaces[@]}" != 0 ] && [ "${#subreplaces[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subgroups[@]}" != 0 ] && [ "${#subgroups[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subdepends[@]}" != 0 ] && [ "${#subdepends[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subrodepends[@]}" != 0 ] && [ "${#subrodepends[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subremoves[@]}" != 0 ] && [ "${#subremoves[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subconflicts[@]}" != 0 ] && [ "${#subconflicts[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subprovides[@]}" != 0 ] && [ "${#subprovides[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subbackup[@]}" != 0 ] && [ "${#subbackup[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#subinstall[@]}" != 0 ] && [ "${#subinstall[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ "${#suboptions[@]}" != 0 ] && [ "${#suboptions[@]}" != "${#subpkgs[@]}" ]; then
-		goodsubpkgs=0
-	fi
-	if [ $goodsubpkgs -eq 1 ]; then
-		i=0
-		for subpkg in "${subpkgs[@]}"
-		do
-			unset pkgdesc license replaces groups depends rodepends removes conflicts provides backup install
-			unset options pkgdesc_localized
-			pkgdesc="${subdescs[$i]}"
-			pkgdesc_localized="${subdescs_localized[$i]}"
-			license="${sublicense[$i]}"
-			replaces="${subreplaces[$i]}"
-			groups="${subgroups[$i]}"
-			depends="${subdepends[$i]}"
-			rodepends="${subrodepends[$i]}"
-			removes="${subremoves[$i]}"
-			conflicts="${subconflicts[$i]}"
-			provides="${subprovides[$i]}"
-			backup="${subbackup[$i]}"
-			install="${subinstall[$i]}"
-			options="${suboptions[$i]}"
-			create_pkg $subpkg
-			i=$(($i+1))
-		done
-	else
-		warning "Subpackage infos are incomplete. Cannot create subpackages."
-	fi
+	i=0
+	for subpkg in "${subpkgs[@]}"
+	do
+		unset pkgdesc license replaces groups depends rodepends removes conflicts provides backup install
+		unset options pkgdesc_localized
+		pkgdesc="${subdescs[$i]}"
+		pkgdesc_localized="${subdescs_localized[$i]}"
+		license="${sublicense[$i]}"
+		replaces="${subreplaces[$i]}"
+		groups="${subgroups[$i]}"
+		depends="${subdepends[$i]}"
+		rodepends="${subrodepends[$i]}"
+		removes="${subremoves[$i]}"
+		conflicts="${subconflicts[$i]}"
+		provides="${subprovides[$i]}"
+		backup="${subbackup[$i]}"
+		install="${subinstall[$i]}"
+		options="${suboptions[$i]}"
+		create_pkg $subpkg
+		i=$(($i+1))
+	done
 fi
 
 cd $startdir
