makepkg: chroot support Date: 2005-08-11 Initial Package Version: 2.9.6 Upstream Status: Not yet submitted Origin: Miklos Vajna <vmiklos@frugalware.org> Description: Adds support for building the package in a chroot.  doc/makepkg.8.in |   55 ++++++++++++++++  etc/makepkg.conf |    5 +  scripts/makepkg  |  178 ++++++++++++++++++++++++++++++++++++++++++++++++++++++-  3 files changed, 237 insertions(+), 1 deletion(-)

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -40,6 +40,12 @@ if [ "$1" = "-F" ]; then
 	shift
 fi
 
+INCHROOT=
+if [ "$1" = "--inchroot" ]; then
+	INCHROOT=1
+	shift
+fi
+
 ### SUBROUTINES ###
 
 plain() {
@@ -183,6 +189,13 @@ handledeps() {
 		else
 			missingdeps=1
 		fi
+	# rerun any additional sh scripts found in /etc/profile.d/
+	for i in /etc/profile.d/*.sh
+	do
+		if [ -x $i ]; then
+			. $i &>/dev/null
+		fi
+	done
 	elif [ "$deplist" != "" -a $haveperm -eq 0 ]; then
 		if [ "$DEP_SRC" = "1" -o "$DEP_BIN" = "1" ]; then
 			warning "Cannot auto-install missing dependencies as a normal user without sudo!"
@@ -217,6 +230,7 @@ usage() {
 	echo "  -o, --nobuild    Download and extract files only"
 	echo "  -p <buildscript> Use an alternate build script (instead of FrugalBuild)"
 	echo "  -r, --rmdeps     Remove installed dependencies after a successful build"
+	echo "  -R, --chroot     Build the package in a chroot environment"
 	echo "  -s, --syncdeps   Install missing dependencies with pacman"
 	echo "  -S, --sudosync   Install missing dependencies with pacman and sudo"
 	echo "  -u, --noup2date  Do not check for newer version"
@@ -228,6 +242,60 @@ usage() {
 	echo
 }
 
+chroot_umount() {
+    msg "Attempting to umount chroot directories..."
+    umount $CHROOTDIR/proc >/dev/null
+    umount $CHROOTDIR/sys >/dev/null
+    umount $CHROOTDIR/dev >/dev/null
+    umount $CHROOTDIR/var/cache/pacman >/dev/null
+    umount $CHROOTDIR/var/cache/ccache/$pkgname >/dev/null
+    if [ "$?" != "0" ]; then
+	error "An error occurred while attempting to umount chroot directories."
+	exit 1
+    fi
+    msg "Successfully umounted chroot directories."
+}
+
+chroot_mount() {
+    msg "Attempting to mount chroot directories..."
+    mount -t proc none $CHROOTDIR/proc >/dev/null &
+    mount -t sysfs none $CHROOTDIR/sys >/dev/null &
+    mount -o bind /dev $CHROOTDIR/dev >/dev/null &
+    mount -o bind /var/cache/pacman $CHROOTDIR/var/cache/pacman >/dev/null &
+    mount -o bind /var/cache/ccache/$pkgname \
+    $CHROOTDIR/var/cache/ccache/$pkgname >/dev/null &
+    if [ "$?" != "0" ]; then
+	error "An error occurred while attempting to mount chroot directories."
+	exit 1
+    fi
+    msg "Successfully mounted chroot directories."
+}
+
+chroot_clean()
+{
+	if [ "$CHROOT" = "1" ]; then
+		msg "Cleaning chroot."
+		rm -rf $CHROOTDIR/var/tmp/fst/*
+		msg "Removing unnecessary packages."
+		for i in "$COREPKGS"
+		do
+			corelist="$corelist `pacman -r $CHROOTDIR -Sg $i|grep -v '^\w'`"
+		done
+		for i in `pacman -r $CHROOTDIR -Q|sed 's/\([^ ]*\) .*/\1/'`
+		do
+			if ! echo $corelist |grep -q $i; then
+				removelist="$removelist $i"
+			fi
+		done
+		if [ ! -z "$removelist" ]; then
+			pacman -r $CHROOTDIR -Rcn $removelist --noconfirm
+			if [ "$?" != "0" ]; then
+				error "Failed to remove packages."
+				exit 1
+			fi
+		fi
+	fi
+}
 
 # Options
 BUILDSCRIPT="./FrugalBuild"
@@ -247,6 +315,7 @@ NODEPS=0
 NOEXTRACT=0
 NOSTRIP=0
 RMDEPS=0
+CHROOT=0
 LOGGING=0
 NOUP2DATE=0
 GZIP=0
@@ -272,6 +341,7 @@ while [ "$#" -ne "0" ]; do
 		--nocolor)    USE_COLOR="n" ;;
 		--genmd5)     GENMD5=1 ;;
 		--rmdeps)     RMDEPS=1 ;;
+		--chroot)     CHROOT=1 ;;
 		--noup2date)  NOUP2DATE=1 ;;
 		--logging)    LOGGING=1 ;;
 		--gzip)       GZIP=1 ;;
@@ -284,7 +354,7 @@ while [ "$#" -ne "0" ]; do
 			exit 1
 			;;
 		-*)
-			while getopts "abBcCdefghij:kl:Lmnop:ursSw:-" opt; do
+			while getopts "abBcCdefghij:kl:Lmnop:urRsSw:-" opt; do
 				case $opt in
 					a) SEARCHDEPS=1 ;;
 					b) DEP_SRC=1 ;;
@@ -309,6 +379,7 @@ while [ "$#" -ne "0" ]; do
 					o) NOBUILD=1 ;;
 					p) BUILDSCRIPT=$OPTARG ;;
 					r) RMDEPS=1 ;;
+					R) CHROOT=1 ;;
 					s) DEP_BIN=1 ;;
 					S) DEP_SUDO=1 ;;
 					u) NOUP2DATE=1 ;;
@@ -350,6 +421,7 @@ if [ "$CLEANCACHE" = "1" ]; then
 	if [ "`id -u`" = "0" -a "$INFAKEROOT" != "1" ]; then
 		msg "Cleaning up source files from the cache."
 		rm -rf /var/cache/pacman/src/*
+		chroot_clean
 		exit 0
 	else
 		error "You must be root to clean the cache."
@@ -448,13 +520,128 @@ if [ -f $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm -a "$FORCE" = "0" -
 	fi
 fi
 
+# Build chroot environment if necessary.
+if [ "$CHROOT" = "1" -a "$INCHROOT" != "1" ]; then
+	if [ "`id -u`" != 0 ]; then
+		error "Building in a chroot as an unprivileged user is not possible."
+		exit 1
+	fi
+	if [ "$CHROOTDIR" = "" ]; then
+		error "The CHROOTDIR environment variable is not defined."
+		exit 1
+	fi
+
+	mkdir -p $CHROOTDIR/{dev,etc,proc,sys,var/cache/pacman,var/tmp/fst}
+
+	if [ -e $CHROOTDIR/var/tmp/fst/lock ]; then
+		error "Somebody already building in this chroot."
+		plain "If you're sure makepkg is not already running, you"
+		plain "can remove $CHROOTDIR/var/tmp/fst/lock."
+		exit 1
+	else
+		touch $CHROOTDIR/var/tmp/fst/lock
+	fi
+
+	install -d -m 2775 {,$CHROOTDIR}/var/cache/ccache/$pkgname
+
+	chroot_mount
+
+	if [ ! -d "$CHROOTDIR/usr" ]; then
+		msg "Building chroot environment"
+		pacman -Syf $COREPKGS -r "$CHROOTDIR" --noconfirm
+		if [ "$?" != "0" ]; then
+			error "Failed to build chroot environment."
+			chroot_umount
+			msg "Removing lock file..."
+			rm -f $CHROOTDIR/var/tmp/fst/lock
+			exit 1
+		fi
+	else
+		msg "Updating the chroot environment"
+		# run pacman -Su twice in case pacman updated
+		pacman -Syu -r "$CHROOTDIR" --noconfirm && \
+			pacman -Su -r "$CHROOTDIR" --noconfirm
+		if [ "$?" != "0" ]; then
+			error "Failed to update chroot environment."
+			chroot_umount
+			msg "Removing lock file..."
+			rm -f $CHROOTDIR/var/tmp/fst/lock
+			exit 1
+		fi
+	fi
+	# why is this necessary?
+	chmod 1777 $CHROOTDIR/tmp
+	
+	msg "Copying config files to chroot"
+	cp -pf /etc/makepkg.conf $CHROOTDIR/etc >/dev/null &
+	cp -pf /etc/resolv.conf $CHROOTDIR/etc >/dev/null &
+	cp -pf /etc/passwd $CHROOTDIR/etc >/dev/null &
+	cp -pf /etc/shadow $CHROOTDIR/etc >/dev/null &
+	cp -pf /etc/group $CHROOTDIR/etc >/dev/null &
+	cp -pf /etc/ld.so.conf $CHROOTDIR/etc >/dev/null &
+	cp -pf /etc/hosts $CHROOTDIR/etc > /dev/null &
+	echo "fst ALL=(ALL)       NOPASSWD: ALL" >$CHROOTDIR/etc/sudoers
+	cp -Ppf /etc/localtime $CHROOTDIR/etc >/dev/null &
+	cp -pf /etc/services $CHROOTDIR/etc > /dev/null &
+	if [ "$?" != "0" ]; then
+		error "An error occurred while attempting to copy config files to chroot."
+		chroot_umount
+		exit 1
+	fi
+	# to make Finclude work
+	if darcs --commands 2>&1|grep -q add; then
+		[ -d $CHROOTDIR/var/tmp/fst/include/ ] || mkdir -p $CHROOTDIR/var/tmp/fst/include/
+		if [ -d `darcs add . 2>&1|sed -n 's/[^/]*/../g; 4 p'`/source/include ]; then
+			cp `darcs add . 2>&1|sed -n 's/[^/]*/../g; 4 p'`/source/include/* $CHROOTDIR/var/tmp/fst/include/
+		elif [ -d $fst_root/$reponame/source/include ]; then
+			cp $fst_root/$reponame/source/include/* $CHROOTDIR/var/tmp/fst/include/
+		fi
+	fi
+
+	msg "Copying $pkgname's buildscript to chroot"
+	cp -a * $CHROOTDIR/var/tmp/fst/
+	chown -R fst:users $CHROOTDIR/var/tmp/fst
+	
+	if [ ! -x  /usr/sbin/chroot ]; then
+		error "chroot was not found."
+	else
+		msg "Entering chroot environment"
+		/usr/sbin/chroot $CHROOTDIR \
+			/bin/su - fst -c "$0 --inchroot -S $ARGLIST"
+	fi
+
+	if [ -f $CHROOTDIR/var/tmp/fst/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm ]; then
+		mv $CHROOTDIR/var/tmp/fst/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm $PKGDEST
+		if [ "`id -u`" = "0" ]; then
+			chown `stat -c %U:%G FrugalBuild` \
+				${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm
+		fi
+		# copy back the buildscript, maybe modified
+		cp $CHROOTDIR/var/tmp/fst/FrugalBuild ./
+		# save the build log if necessary
+		if [ -f $CHROOTDIR/var/tmp/fst/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.log ]; then
+			mv $CHROOTDIR/var/tmp/fst/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.log ./
+		fi
+		rm -rf $CHROOTDIR/var/tmp/fst/*
+		chroot_clean
+	fi
+
+	chroot_umount
+	rm -f $CHROOTDIR/var/tmp/fst/lock
+	exit 0
+fi
+
 # Enter the fakeroot environment if necessary.  This will call the makepkg script again
 # as the fake root user.  We detect this by passing a sentinel option (-F) to makepkg
 if [ "`id -u`" != "0" ]; then
 	if [ "$USE_FAKEROOT" = "y" -o "$USE_FAKEROOT" = "Y" ]; then
 		if [ `type -p fakeroot` ]; then
 			msg "Entering fakeroot environment"
-			fakeroot -- $0 -F $ARGLIST
+			if [ "$INCHROOT" != "1" ]; then
+				fakeroot -- $0 -F $ARGLIST
+			else
+				fakeroot -- $0 -F --inchroot $ARGLIST
+			fi
 			exit $?
 		else
 			warning "Fakeroot is not installed.  Building as an unprivileged user"
@@ -693,6 +880,10 @@ fi
 # use ccache if it's available
 if [ "$NOCCACHE" = "0" ]; then
 	[ -d /usr/lib/ccache/bin ] && export PATH=/usr/lib/ccache/bin:$PATH
+	install -d -m 2775 /var/cache/ccache/$pkgname
+	export CCACHE_DIR=/var/cache/ccache/$pkgname
+	export CCACHE_NOLINK=1
+	export CCACHE_UMASK=002
 fi
 
 # build
@@ -868,8 +1059,13 @@ fi
 if [ -f $startdir/pkg/.CHANGELOG ]; then
 	extra="$extra .CHANGELOG"
 fi
+if [ "$INCHROOT" != "1" ]; then
 tar czvf $PKGDEST/$pkgname-$pkgver-$pkgrel-$CARCH.fpm .PKGINFO .FILELIST \
 	$extra * | sort >../filelist
+else
+	tar czvf ../$pkgname-$pkgver-$pkgrel-$CARCH.fpm .PKGINFO .FILELIST \
+		$extra * | sort >../filelist
+fi
 
 cd $startdir
 if [ "$SEARCHDEPS" == "1" ]; then
