pacman: sha1sum support   * Added sha1sum support patch into makepkg

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -218,7 +218,8 @@ usage() {
 	echo "  -d, --nodeps     Skip all dependency checks"
 	echo "  -e, --noextract  Do not extract source files (use existing src/ dir)"
 	echo "  -f, --force      Overwrite existing package"
-	echo "  -g, --genmd5     Generate MD5sums for source files"
+	echo "  -g, --gensha1    Generate SHA1sums for source files"
+	echo "  -G, --genmd5     Generate MD5sums for source files"
 	echo "  -h, --help       This help"
 	echo "  -i, --install    Install package after successful build"
 	echo "  -j <jobs>        Set MAKEFLAGS to \"-j<jobs>\" before building"
@@ -305,6 +306,7 @@ DEP_BIN=0
 DEP_SRC=0
 DEP_SUDO=0
 FORCE=0
+GENSHA1=0
 GENMD5=0
 INSTALL=0
 DOWNLOAD=""
@@ -339,6 +341,7 @@ while [ "$#" -ne "0" ]; do
 		--nostrip)    NOSTRIP=1 ;;
 		--nobuild)    NOBUILD=1 ;;
 		--nocolor)    USE_COLOR="n" ;;
+		--gensha1)    GENSHA1=1 ;;
 		--genmd5)     GENMD5=1 ;;
 		--rmdeps)     RMDEPS=1 ;;
 		--chroot)     CHROOT=1 ;;
@@ -354,7 +357,7 @@ while [ "$#" -ne "0" ]; do
 			exit 1
 			;;
 		-*)
-			while getopts "abBcCdefghij:kl:Lmnop:urRsSw:-" opt; do
+			while getopts "abBcCdefgGhij:kl:Lmnop:urRsSw:-" opt; do
 				case $opt in
 					a) SEARCHDEPS=1 ;;
 					b) DEP_SRC=1 ;;
@@ -364,7 +367,8 @@ while [ "$#" -ne "0" ]; do
 					d) NODEPS=1 ;;
 					e) NOEXTRACT=1 ;;
 					f) FORCE=1 ;;
-					g) GENMD5=1 ;;
+					g) GENSHA1=1 ;;
+					G) GENMD5=1 ;;
 					h)
 						usage
 						exit 0
@@ -509,7 +513,7 @@ if [ "$install" -a ! -f "$install" ]; then
 	exit 1
 fi
 
-if [ -f $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm -a "$FORCE" = "0" -a "$GENMD5" = "0" ]; then
+if [ -f $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm -a "$FORCE" = "0" -a "$GENMD5" = "0" -a "$GENSHA1" = "0" ]; then
 	if [ "$INSTALL" = "1" ]; then
 		warning "a package has already been built, installing existing package."
 		pacman --upgrade $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm
@@ -744,39 +748,66 @@ for netfile in ${source[@]}; do
 	fi
 done
 
-if [ "$GENMD5" = "0" ]; then
+if [ "$GENMD5" = "0" -a "$GENSHA1" = "0" ]; then
 	if [ "$NOEXTRACT" = "1" ]; then
 		warning "Skipping source extraction       -- using existing src/ tree"
 		warning "Skipping source integrity checks -- using existing src/ tree"
 	else
+		# SHA1 validation
+		if [ ${#sha1sums[@]} -eq ${#source[@]} ]; then
+			if [ `type -p sha1sum` ]; then
+				msg "Validating source files with SHA1sums"
+				errors=0
+				idx=0
+				for netfile in ${source[@]}; do
+					file=`strip_url $netfile`
+					echo -n "    $file ... " >&2
+					echo "${sha1sums[$idx]}  $file" | sha1sum -c - >/dev/null 2>&1
+					if [ $? -ne 0 ]; then
+						echo "FAILED" >&2
+						errors=1
+					else
+						echo "Passed" >&2
+					fi
+					idx=$(($idx+1))
+				done
+				if [ $errors -gt 0 ]; then
+					error "One or more files did not pass the validity check!"
+					exit 1
+				fi
+			else
+				warning "The sha1sum program is missing.  Cannot verify source files!"
+				sleep 1
+			fi
 		# MD5 validation
-		if [ ${#md5sums[@]} -ne ${#source[@]} ]; then
-			warning "MD5sums are missing or incomplete.  Cannot verify source integrity."
-			#sleep 1
-		elif [ `type -p md5sum` ]; then
-			msg "Validating source files with MD5sums"
-			errors=0
-			idx=0
-			for netfile in ${source[@]}; do
-				file=`strip_url $netfile`
-				echo -n "    $file ... " >&2
-				echo "${md5sums[$idx]}  $file" | md5sum -c - >/dev/null 2>&1
-				if [ $? -ne 0 ]; then
+		elif [ ${#md5sums[@]} -eq ${#source[@]} ]; then
+			if [ `type -p md5sum` ]; then
+				msg "Validating source files with MD5sums"
+				errors=0
+				idx=0
+				for netfile in ${source[@]}; do
+					file=`strip_url $netfile`
+					echo -n "    $file ... " >&2
+					echo "${md5sums[$idx]}  $file" | md5sum -c - >/dev/null 2>&1+                                       if [ $? -ne 0 ]; then
 					echo "FAILED" >&2
 					errors=1
-				else
-					echo "Passed" >&2
-				fi	
-				idx=$(($idx+1))
-			done
-			if [ $errors -gt 0 ]; then
-				error "One or more files did not pass the validity check!"
-				exit 1
+					else
+						echo "Passed" >&2
+					fi
+					idx=$(($idx+1))
+				done
+				if [ $errors -gt 0 ]; then
+					error "One or more files did not pass the validity check!"
+					exit 1
+				fi
+			else
+				warning "The md5sum program is missing.  Cannot verify source files!"
+				sleep 1
 			fi
 		else
-			warning "The md5sum program is missing.  Cannot verify source files!"
-			sleep 1
+			warning "MD5sums and SHA1sums are missing or incomplete.  Cannot verify source integrity."
 		fi
+
 		# extract sources
 		msg "Extracting Sources..."
 		for netfile in ${source[@]}; do
@@ -814,6 +845,7 @@ if [ "$GENMD5" = "0" ]; then
 	fi
 else
 # generate md5 hashes
+    if [ "$GENMD5" = "1" ]; then
 	if [ ! `type -p md5sum` ]; then
 		error "Cannot find the md5sum program."
 		exit 1
@@ -849,8 +881,38 @@ else
 	done
 	plain ""
 	exit 0
+    # generate sha1 hashes
+    elif [ "$GENSHA1" = "1" ]; then
+	if [ ! `type -p sha1sum` ]; then
+		error "Cannot find the sha1sum program."
+		exit 1
+	fi
+	msg "Generating SHA1sums for source files"
+	plain ""
+	ct=0
+	newline=0
+	numsrc=${#source[@]}
+	for netfile in ${source[@]}; do
+		file=`strip_url $netfile`
+		sum=`sha1sum $file | cut -d' ' -f 1`
+		if [ $ct -eq 0 ]; then
+			echo -n "sha1sums=("
+		else
+			echo -ne "\t  "
+		fi
+		echo -n "'$sum'"
+		ct=$(($ct+1))
+		if [ $ct -eq $numsrc ]; then
+			echo ')'
+		else
+			echo ' \'
+			newline=0
+		fi
+	done
+	plain ""
+	exit 0
+    fi
 fi
-
 
 if [ "`id -u`" = "0" ]; then
 	# chown all source files to root.root
