makepkg: some simple caching support if rsync available

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -52,7 +52,8 @@ LOGGING=0
 NOUP2DATE=0
 GZIP=0
 NODOCS=0
-TREE="current"
+TREE=""
+CACHEURL=""
 
 PACMAN_OPTS=
 
@@ -61,6 +62,7 @@ PACMAN_OPTS=
 
 # repoman.conf for $fst_root
 [ -f /etc/repoman.conf ] && source /etc/repoman.conf
+[ -n "$repos" ] && TREE="$repos"
 
 # makepkg configuration
 [ -f /etc/makepkg.conf ] && source /etc/makepkg.conf
@@ -263,6 +265,7 @@ usage() {
 	echo
 	echo "Options:"
 	echo "  -a, --searchdeps Search for package dependencies automatically"
+	echo "  -A <url>         rsync cache url to use before downloading anything"
 	echo "  -b, --builddeps  Build missing dependencies from source"
 	echo "  -B, --noccache   Do not use ccache during build"
 	echo "  -c, --clean      Clean up work files after build"
@@ -601,9 +604,10 @@ while [ "$#" -ne "0" ]; do
 			exit 1
 			;;
 		-*)
-			while getopts "abBcCdD:efgGhij:kl:Lmnop:urRHsSt:w:-" opt; do
+			while getopts "aA:bBcCdD:efgGhij:kl:Lmnop:urRHsSt:w:-" opt; do
 				case $opt in
 					a) SEARCHDEPS=1 ;;
+					A) CACHEURL=$OPTARG ;;
 					b) DEP_SRC=1 ;;
 					B) NOCCACHE=1 ;;
 					c) CLEANUP=1 ;;
@@ -794,6 +798,11 @@ fi
 if ! in_array $CARCH ${archs[@]}; then
 	error "$pkgname is not available on $CARCH."
 	exit 1
+fi
+
+serverlist=${TREE}_servers
+if [ -z "$CACHEURL" ]; then
+	CACHEURL="${!serverlist}/source/$groups/$pkgname"
 fi
 
 if [ ! -z "$subpkgs" ]; then
@@ -1134,12 +1143,28 @@ for netfile in "${source[@]}" "${signatures[@]}"; do
 			msg "Aborting..."
 			exit 1
 		fi
-		msg "    Downloading $file"
-		$FTPAGENT "$netfile" 2>&1
+		# try to download the file from the cache server
+		if [ "`type -p rsync`" -a -n "$CACHEURL" ]; then
+			# check if the file is there
+			rsync $CACHEURL/$file &>/dev/null
+			if [ "$?" = "0" ]; then
+				rsync -avP $CACHEURL/$file ./
+				if [ ! -f "$file" ]; then
+					error "Failed to download $file from cache while it is there"
+					msg "Aborting..."
+					exit 1
+				fi
+			fi
+		fi
+		# if failed to retreive from cache download it from the master server
 		if [ ! -f "$file" ]; then
-			error "Failed to download $file"
-			msg "Aborting..."
-			exit 1
+			msg "    Downloading $file"
+			$FTPAGENT "$netfile" 2>&1
+			if [ ! -f "$file" ]; then
+				error "Failed to download $file"
+				msg "Aborting..."
+				exit 1
+			fi
 		fi
 		if [ "`id -u`" = "0" -a "$INFAKEROOT" != "1" ]; then
 			mkdir -p /var/cache/pacman/src && cp "$file" /var/cache/pacman/src
