Add Write SHA1 option which will write SHA1 at the end of the file. Added the option --wrtsha1/-G to generate and *write* sha1shum in FrugalBuild The sha1 will only replace an existing sha1sums() array and not a complex one.

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -272,6 +272,7 @@ usage() {
 	echo "  -e, --noextract  Do not extract source files (use existing src/ dir)"
 	echo "  -f, --force      Overwrite existing package"
 	echo "  -g, --gensha1    Generate SHA1sums for source files"
+	echo "  -G, --wrtsha1    Generate SHA1sums for source files and add it to the build script"
 	echo "  -h, --help       This help"
 	echo "  -i, --install    Install package after successful build"
 	echo "  -j <jobs>        Set MAKEFLAGS to \"-j<jobs>\" before building"
@@ -583,7 +584,8 @@ while [ "$#" -ne "0" ]; do
 		--nostrip)    NOSTRIP=1 ;;
 		--nobuild)    NOBUILD=1 ;;
 		--nocolor)    USE_COLOR="n" ;;
-		--gensha1)    GENSHA1=1 ;;
+		--gensha1)    GENSHA1=1; CHROOT=0 ;;
+		--wrtsha1)    GENSHA1=1; WRITESHA1=1; CHROOT=0 ;;
 		--rmdeps)     RMDEPS=1 ;;
 		--chroot)     CHROOT=1 ;;
 		--host)       CHROOT=0 ;;
@@ -599,7 +601,7 @@ while [ "$#" -ne "0" ]; do
 			exit 1
 			;;
 		-*)
-			while getopts "abBcCdD:efghij:kl:Lmnop:urRHsSt:w:-" opt; do
+			while getopts "abBcCdD:efgGhij:kl:Lmnop:urRHsSt:w:-" opt; do
 				case $opt in
 					a) SEARCHDEPS=1 ;;
 					b) DEP_SRC=1 ;;
@@ -611,6 +613,7 @@ while [ "$#" -ne "0" ]; do
 					e) NOEXTRACT=1 ;;
 					f) FORCE=1 ;;
 					g) GENSHA1=1; CHROOT=0 ;;
+					G) GENSHA1=1; WRITESHA1=1; CHROOT=0 ;;
 					h)
 						usage
 						exit 0
@@ -1264,25 +1267,52 @@ else
 		ct=0
 		newline=0
 		numsrc=${#source[@]}
-		for netfile in "${source[@]}"; do
-			file=`strip_url "$netfile"`
-			sum=`sha1sum "$file" | cut -d' ' -f 1`
+		for netfile in ${source[@]}; do
+			file=$(strip_url $netfile)
+			sum=$(sha1sum $file | cut -d' ' -f 1)
 			if [ $ct -eq 0 ]; then
-				echo -n "sha1sums=("
+				SHA1SUMS="sha1sums=("
 			else
-				echo -ne "\t  "
+				SHA1SUMS="${SHA1SUMS}"
 			fi
-			echo -n "'$sum'"
+			SHA1SUMS="${SHA1SUMS}'${sum}'"
 			ct=$(($ct+1))
 			if [ $ct -eq $numsrc ]; then
-				echo ')'
+				SHA1SUMS="${SHA1SUMS})"
 			else
-				echo ' \'
-				newline=0
+				# Don't be afraid but \\\n instead of \n coz of the \\ a little below
+				# \\\n would give \n (printed) but \\\\\n will give \
+				# and a new line carriage '\n' (i.e '\''\n')
+				SHA1SUMS="${SHA1SUMS}\\\\\n          "
 			fi
 		done
-	plain ""
-	exit 0
+		echo -e "${SHA1SUMS}"
+		plain ""
+		if [ "${WRITESHA1}" = 1 ]; then
+            cd ${startdir}
+            if [ "`grep -c sha1sums= ${BUILDSCRIPT}`" -gt 1 ]; then
+                error "${BUILDSCRIPT} contain more than one sha1sums, please update manually"
+                exit 1
+            fi
+            if grep -q sha1sums= ${BUILDSCRIPT}; then
+                Fmessage "updating \$sha1sums() in the FrugalBuild."
+                if grep -q '^sha1sums.*)' ${BUILDSCRIPT}; then
+                    sed -i "/^sha1sums.*)/d" ${BUILDSCRIPT}
+                else
+                    sed -i "/^sha1sums/,/)/d" ${BUILDSCRIPT}
+                fi
+				if grep -q "# optimization" "${BUILDSCRIPT}" ; then
+					# Always keep this line at the end
+					sed -i "s@^# optimization OK.*@${SHA1SUMS}\n# optimization OK@g" ${BUILDSCRIPT}
+				else
+					echo -e "${SHA1SUMS}" >> ${BUILDSCRIPT}
+				fi
+            else
+                error "Initial \$sha1sums() array does not exist, Aborting..."
+                exit 1
+            fi
+		fi
+		exit 0
 	fi
 fi
 
